### ISSUE TITLE
Test Phase

### ISSUE THREAD

**Issue by zeinaabuaisheh** [ivegner/PyDSRL#3]
Hello,

I would like to know how the code could be tested after the training is finished?

Thanks

**Comment by chesternimiz** [comment]
Hello, sorry I can't help you and I'm here for help. Did you successfully train with main.py? When I ran main.py, I got many error messages with tensor shapes. Have you met such errors and can you successfully train with main.py? Thanks.

**Comment by ivegner** [comment]
Hi, I've updated PyDSRL to run on Python 3.8.5, with instructions and some bugfixes. It now runs, please check the README. There are still bugs, which I do not have time to fix right now -- please feel free to submit PRs.
