### ISSUE TITLE
Environment Problem

### ISSUE THREAD

**Issue by JunbZhang** [ivegner/PyDSRL#4]
Hi ivegner,
 I have some problems with PyDSRL when I'm trying to reproduce the Python environment by following your requirements.txt. 
Could you please specify the packages' version in requirements.txt? And what Python version to run the program? 
Thanks!

**Comment by ivegner** [comment]
I'm super busy right now -- earliest I'll get to this is December. Sorry!

I believe it was run with 3.6.

**Comment by ivegner** [comment]
Hi, I've updated PyDSRL to run on Python 3.8.5, with instructions and some bugfixes. It now runs, please check the README. There are still bugs, which I do not have time to fix right now -- please feel free to submit PRs.
