### ISSUE TITLE
How to run your program?

### ISSUE THREAD

**Issue by muyuuuu** [ivegner/PyDSRL#5]
How to run your program? Should I to create a virtual environment named `CrossCircle-MixedRand-v0` ?

I'm running: `python main.py`, It got errpr: `layout() got an unexpected keyword argument 'num_entities'` in line 56: 
`states.append(temp_env.make_random_state(min_entities, max_entities))`

**Comment by ivegner** [comment]
Hi, I've updated PyDSRL to run on Python 3.8.5, with instructions and some bugfixes. It now runs, please check the README. There are still bugs, which I do not have time to fix right now -- please feel free to submit PRs.

**Comment by JunbZhang** [comment]
xxx
